### ISSUE TITLE
Composer JSON asks for version 2 of  liip/search-bundle

### ISSUE THREAD

**Issue by larrylaptop** [liip/LiipHelloBundle#20]
liip/search-bundle is add version 1.0.2 if i'm not mistaken... so the bundel will not install with composer

**Comment by lsmith77** [comment]
it should as the minimal stability is set to dev in the composer.json

if you require this Bundle in your own composer.json its your responsibility to then either also set the minimal stability or explicitly allow the beta version of the search bundle
