### ISSUE TITLE
Your requirements could not be resolved to an installable set of packages.

### ISSUE THREAD

**Issue by mateuszkasiubajisc** [liip/LiipHelloBundle#21]
During installation - php composer.phar require liip/hello-bundle:dev-master i received this problem. 

Problem 1
    - Installation request for liip/hello-bundle dev-master -> satisfiable by liip/hello-bundle[dev-master].
    - liip/hello-bundle dev-master requires friendsofsymfony/user-bundle ~2.0 -> satisfiable by friendsofsymfony/user-bundle[2.0.x-dev, v2.0.0-alpha1, v2.0.0-alpha2, v2.0.0-alpha3] but these conflict with your requirements or minimum-stability.

**Comment by gustawdaniel** [comment]
I have the same error:

```
composer require liip/hello-bundle:dev-master
./composer.json has been created
Loading composer repositories with package information
Updating dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - Installation request for liip/hello-bundle dev-master -> satisfiable by liip/hello-bundle[dev-master].
    - liip/hello-bundle dev-master requires friendsofsymfony/user-bundle ~2.0 -> no matching package found.

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

Installation failed, deleting ./composer.json.
```

You can solve this problem appending `composer.lock` to repo along to doc from 
[getcomposer.org](https://getcomposer.org/doc/01-basic-usage.md)

> Commit your application's composer.lock (along with composer.json) into version control.

> This is important because the install command checks if a lock file is present, and if it is, it downloads the versions specified there (regardless of what composer.json says).

**Comment by lsmith77** [comment]
this bundle is just for demo purposes .. that being said .. it does depend on some packages that are not yet stable in the required version .. in order to install them, you need to lower your stability level or explicitly allow these into your composer.json

**Comment by Chrisissorry** [comment]
I have the same problem and I did not quite understand how to solve this. My composer.json looks like this:

`
{
  "minimum-stability": "dev",
  "require": {
    "liip/hello-bundle": "dev-master"
  }
}
`

So the minimum-stability version is the lowest you can get, right?

Still: 

`Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - doctrine/phpcr-odm 1.4.x-dev requires phpcr/phpcr-implementation ^2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.4.0 requires phpcr/phpcr-implementation ^2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.3.2 requires phpcr/phpcr-implementation ^2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.3.1 requires phpcr/phpcr-implementation ^2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.3.0-rc4 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.3.0-rc3 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.3.0-rc2 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.3.0-rc requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.3.0 requires phpcr/phpcr-implementation ^2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.x-dev requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.6 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.5 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.4 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.3 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.2 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.1 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.0-rc6 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.0-rc5 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.0-rc4 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.0-rc3 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.0-rc2 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.0-RC1 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.2.0 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.1.x-dev requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.1.4 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.1.3 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.1.2 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.1.1 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.1.0-beta2 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.1.0-beta1 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.1.0-RC2 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.1.0-RC1 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.1.0 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.0.x-dev requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.0.2 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.0.1 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - doctrine/phpcr-odm 1.0.0-beta5 requires phpcr/phpcr-implementation >=2.1.0-beta3,<2.2.0-dev -> no matching package found.
    - doctrine/phpcr-odm 1.0.0-beta4 requires phpcr/phpcr-implementation >=2.1.0-beta3,<2.2.0-dev -> no matching package found.
    - doctrine/phpcr-odm 1.0.0-beta3 requires phpcr/phpcr-implementation >=2.1.0-beta3,<2.2.0-dev -> no matching package found.
    - doctrine/phpcr-odm 1.0.0-beta2 requires phpcr/phpcr-implementation >=2.1.0-beta3,<2.2.0-dev -> no matching package found.
    - doctrine/phpcr-odm 1.0.0-beta1 requires phpcr/phpcr-implementation >=2.1.0-beta3,<2.2.0-dev -> no matching package found.
    - doctrine/phpcr-odm 1.0.0-alpha2 requires phpcr/phpcr-implementation >=2.1.0-beta3,<2.2.0-dev -> no matching package found.
    - doctrine/phpcr-odm 1.0.0-alpha1 requires phpcr/phpcr-implementation >=2.1.0-beta3,<2.2.0-dev -> no matching package found.
    - doctrine/phpcr-odm 1.0.0-RC5 requires phpcr/phpcr-implementation ~2.1.0-RC1 -> no matching package found.
    - doctrine/phpcr-odm 1.0.0-RC4 requires phpcr/phpcr-implementation ~2.1.0-RC1 -> no matching package found.
    - doctrine/phpcr-odm 1.0.0-RC3 requires phpcr/phpcr-implementation ~2.1.0-RC1 -> no matching package found.
    - doctrine/phpcr-odm 1.0.0-RC2 requires phpcr/phpcr-implementation ~2.1.0-RC1 -> no matching package found.
    - doctrine/phpcr-odm 1.0.0-RC1 requires phpcr/phpcr-implementation ~2.1.0-RC1 -> no matching package found.
    - doctrine/phpcr-odm 1.0.0 requires phpcr/phpcr-implementation ~2.1.0 -> no matching package found.
    - liip/hello-bundle dev-master requires doctrine/phpcr-odm ~1.0 -> satisfiable by doctrine/phpcr-odm[1.0.0, 1.0.0-RC1, 1.0.0-RC2, 1.0.0-RC3, 1.0.0-RC4, 1.0.0-RC5, 1.0.0-alpha1, 1.0.0-alpha2, 1.0.0-beta1, 1.0.0-beta2, 1.0.0-beta3, 1.0.0-beta4, 1.0.0-beta5, 1.0.1, 1.0.2, 1.0.x-dev, 1.1.0, 1.1.0-RC1, 1.1.0-RC2, 1.1.0-beta1, 1.1.0-beta2, 1.1.1, 1.1.2, 1.1.3, 1.1.4, 1.1.x-dev, 1.2.0, 1.2.0-RC1, 1.2.0-rc2, 1.2.0-rc3, 1.2.0-rc4, 1.2.0-rc5, 1.2.0-rc6, 1.2.1, 1.2.2, 1.2.3, 1.2.4, 1.2.5, 1.2.6, 1.2.x-dev, 1.3.0, 1.3.0-rc, 1.3.0-rc2, 1.3.0-rc3, 1.3.0-rc4, 1.3.1, 1.3.2, 1.4.0, 1.4.x-dev].
    - Installation request for liip/hello-bundle @dev -> satisfiable by liip/hello-bundle[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://getcomposer.org/doc/04-schema.md#minimum-stability> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.`

**Comment by remedge** [comment]
@Chrisissorry i've got the same issue and opened the new issue — https://github.com/liip/LiipHelloBundle/issues/26
